//! Bulk operations for City entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateCityDto;
use crate::application::service::CityService;
use crate::domain::entity::City;

/// Bulk operation handler for City entities.
///
/// Wraps `CityService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type CityBulkService = GenericBulkService<City, CreateCityDto, CityService>;

// <<< CUSTOM
// END CUSTOM
