//! Bulk operations for Country entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateCountryDto;
use crate::application::service::CountryService;
use crate::domain::entity::Country;

/// Bulk operation handler for Country entities.
///
/// Wraps `CountryService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type CountryBulkService = GenericBulkService<Country, CreateCountryDto, CountryService>;

// <<< CUSTOM
// END CUSTOM
