//! Bulk operations for District entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateDistrictDto;
use crate::application::service::DistrictService;
use crate::domain::entity::District;

/// Bulk operation handler for District entities.
///
/// Wraps `DistrictService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type DistrictBulkService = GenericBulkService<District, CreateDistrictDto, DistrictService>;

// <<< CUSTOM
// END CUSTOM
