//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod city_bulk;
pub mod country_bulk;
pub mod district_bulk;
pub mod province_bulk;
pub mod subdistrict_bulk;

pub use city_bulk::CityBulkService;
pub use country_bulk::CountryBulkService;
pub use district_bulk::DistrictBulkService;
pub use province_bulk::ProvinceBulkService;
pub use subdistrict_bulk::SubdistrictBulkService;

// <<< CUSTOM
// END CUSTOM
