//! Bulk operations for Subdistrict entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateSubdistrictDto;
use crate::application::service::SubdistrictService;
use crate::domain::entity::Subdistrict;

/// Bulk operation handler for Subdistrict entities.
///
/// Wraps `SubdistrictService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type SubdistrictBulkService = GenericBulkService<Subdistrict, CreateSubdistrictDto, SubdistrictService>;

// <<< CUSTOM
// END CUSTOM
