//! Country DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Country;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Country
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateCountryDto {
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub isocode: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub phonecode: i32,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Country
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateCountryDto {
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub isocode: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub phonecode: i32,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Country
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchCountryDto {
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub isocode: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub phonecode: Option<i32>,
}

impl PatchCountryDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.isocode.is_some() || self.name.is_some() || self.phonecode.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Country entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CountryResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub isocode: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub phonecode: i32,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Country entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CountryListResponseDto {
    /// List of items
    pub items: Vec<CountryResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl CountryListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<CountryResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct CountrySummaryDto {
    pub id: Uuid,
    pub isocode: String,
    pub name: String,
    pub phonecode: i32,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Country> for CountryResponseDto {
    fn from(entity: Country) -> Self {
        Self {
            id: entity.id,
            isocode: entity.isocode,
            name: entity.name,
            phonecode: entity.phonecode,
            metadata: entity.metadata,
        }
    }
}

impl From<Country> for CountrySummaryDto {
    fn from(entity: Country) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            isocode: entity.isocode,
            name: entity.name,
            phonecode: entity.phonecode,
            created_at,
        }
    }
}

impl From<CreateCountryDto> for Country {
    fn from(dto: CreateCountryDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            isocode: dto.isocode,
            name: dto.name,
            phonecode: dto.phonecode,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Country> for CountryResponseDto {
    fn from(entity: &Country) -> Self {
        Self {
            id: entity.id.clone(),
            isocode: entity.isocode.clone(),
            name: entity.name.clone(),
            phonecode: entity.phonecode.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateCountryDto> for Country {
    fn from_create_dto(dto: CreateCountryDto) -> backbone_core::ServiceResult<Self> {
        Ok(Country::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateCountryDto> for Country {
    fn apply_update(mut self, dto: UpdateCountryDto) -> backbone_core::ServiceResult<Self> {
        self.isocode = dto.isocode;
        self.name = dto.name;
        self.phonecode = dto.phonecode;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Country here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
