//! Subdistrict DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Subdistrict;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Subdistrict
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSubdistrictDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "country_id")]
    pub country_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "province_id")]
    pub province_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "city_id")]
    pub city_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "district_id")]
    pub district_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "postal_code")]
    pub postal_code: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latitude: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub longitude: Option<Decimal>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Subdistrict
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSubdistrictDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "country_id")]
    pub country_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "province_id")]
    pub province_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "city_id")]
    pub city_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "district_id")]
    pub district_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "postal_code")]
    pub postal_code: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub latitude: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub longitude: Option<Decimal>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Subdistrict
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSubdistrictDto {
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "country_id")]
    pub country_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "province_id")]
    pub province_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "city_id")]
    pub city_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "district_id")]
    pub district_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "postal_code")]
    pub postal_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub latitude: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub longitude: Option<Decimal>,
}

impl PatchSubdistrictDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.country_id.is_some() || self.province_id.is_some() || self.city_id.is_some() || self.district_id.is_some() || self.postal_code.is_some() || self.latitude.is_some() || self.longitude.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Subdistrict entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SubdistrictResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub country_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub province_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub city_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub district_id: Uuid,
    pub postal_code: Option<String>,
    pub latitude: Option<Decimal>,
    pub longitude: Option<Decimal>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Subdistrict entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SubdistrictListResponseDto {
    /// List of items
    pub items: Vec<SubdistrictResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SubdistrictListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SubdistrictResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SubdistrictSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub country_id: Uuid,
    pub province_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Subdistrict> for SubdistrictResponseDto {
    fn from(entity: Subdistrict) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            country_id: entity.country_id,
            province_id: entity.province_id,
            city_id: entity.city_id,
            district_id: entity.district_id,
            postal_code: entity.postal_code,
            latitude: entity.latitude,
            longitude: entity.longitude,
            metadata: entity.metadata,
        }
    }
}

impl From<Subdistrict> for SubdistrictSummaryDto {
    fn from(entity: Subdistrict) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            country_id: entity.country_id,
            province_id: entity.province_id,
            created_at,
        }
    }
}

impl From<CreateSubdistrictDto> for Subdistrict {
    fn from(dto: CreateSubdistrictDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            country_id: dto.country_id,
            province_id: dto.province_id,
            city_id: dto.city_id,
            district_id: dto.district_id,
            postal_code: dto.postal_code,
            latitude: dto.latitude,
            longitude: dto.longitude,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Subdistrict> for SubdistrictResponseDto {
    fn from(entity: &Subdistrict) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            country_id: entity.country_id.clone(),
            province_id: entity.province_id.clone(),
            city_id: entity.city_id.clone(),
            district_id: entity.district_id.clone(),
            postal_code: entity.postal_code.clone(),
            latitude: entity.latitude.clone(),
            longitude: entity.longitude.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSubdistrictDto> for Subdistrict {
    fn from_create_dto(dto: CreateSubdistrictDto) -> backbone_core::ServiceResult<Self> {
        Ok(Subdistrict::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSubdistrictDto> for Subdistrict {
    fn apply_update(mut self, dto: UpdateSubdistrictDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.country_id = dto.country_id;
        self.province_id = dto.province_id;
        self.city_id = dto.city_id;
        self.district_id = dto.district_id;
        self.postal_code = dto.postal_code;
        self.latitude = dto.latitude;
        self.longitude = dto.longitude;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Subdistrict here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
