//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod city_specification;
pub mod country_specification;
pub mod district_specification;
pub mod province_specification;
pub mod subdistrict_specification;

// <<< CUSTOM
// END CUSTOM
