//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod city_domain_policy;
pub mod country_domain_policy;
pub mod district_domain_policy;
pub mod province_domain_policy;
pub mod subdistrict_domain_policy;

pub use city_domain_policy::CityDomainPolicy;
pub use country_domain_policy::CountryDomainPolicy;
pub use district_domain_policy::DistrictDomainPolicy;
pub use province_domain_policy::ProvinceDomainPolicy;
pub use subdistrict_domain_policy::SubdistrictDomainPolicy;

// <<< CUSTOM
// END CUSTOM
