//! Application service for District entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `district_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateDistrictDto, UpdateDistrictDto};
use crate::domain::entity::District;
use crate::infrastructure::persistence::DistrictRepository;

/// Application service for District entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `district_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct DistrictServiceCustom {
///     inner: Arc<DistrictService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type DistrictService = GenericCrudService<
    District,
    CreateDistrictDto,
    UpdateDistrictDto,
    DistrictRepository,
>;

// <<< CUSTOM
// END CUSTOM
