//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod city_service;
pub mod country_service;
pub mod district_service;
pub mod province_service;
pub mod subdistrict_service;

// <<< CUSTOM
pub mod geo_readiness;
// END CUSTOM

pub use city_service::CityService;
pub use country_service::CountryService;
pub use district_service::DistrictService;
pub use province_service::ProvinceService;
pub use subdistrict_service::SubdistrictService;
// <<< CUSTOM
pub use geo_readiness::{ancestor_drift_count, geo_readiness_check, GeoReadinessError};
// END CUSTOM