//! Application service for Province entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `province_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateProvinceDto, UpdateProvinceDto};
use crate::domain::entity::Province;
use crate::infrastructure::persistence::ProvinceRepository;

/// Application service for Province entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `province_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ProvinceServiceCustom {
///     inner: Arc<ProvinceService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ProvinceService = GenericCrudService<
    Province,
    CreateProvinceDto,
    UpdateProvinceDto,
    ProvinceRepository,
>;

// <<< CUSTOM
// END CUSTOM
