-- Country Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the countries table.
-- Customize this file to add your initial data.

-- INSERT INTO geo.countries (
--     id,
--     isocode,
--     name,
--     phonecode,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO geo.countries (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

INSERT INTO geo.countries (id, metadata, isocode, name, phonecode) VALUES
('866f1b4e-a9f3-4626-95d1-13c183916b4b', '{"created_at": "2024-12-02T15:22:25Z", "updated_at": "2024-12-02T15:22:25Z"}', 'ID', 'Indonesia', 62);