-- Province Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the provinces table.
-- Customize this file to add your initial data.

-- INSERT INTO geo.provinces (
--     id,
--     name,
--     country_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO geo.provinces (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

INSERT INTO geo.provinces (id, metadata, name, country_id) VALUES
('4da59c52-fb04-4ed0-a031-013d4fab602a', '{"created_at": "2024-12-02T15:22:25Z", "updated_at": "2024-12-02T15:22:25Z"}', 'Aceh', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('c5e4eb34-f28a-4feb-bbc6-c2a3dff417df', '{"created_at": "2024-12-02T15:23:58Z", "updated_at": "2024-12-02T15:23:58Z"}', 'Bali', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('ebd1c7b1-20be-4d01-b655-9ee3ea4523d0', '{"created_at": "2024-12-02T15:23:55Z", "updated_at": "2024-12-02T15:23:55Z"}', 'Banten', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('e0d2c839-0d14-4c01-b022-f4845eee9e25', '{"created_at": "2024-12-02T15:22:59Z", "updated_at": "2024-12-02T15:22:59Z"}', 'Bengkulu', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('c3ba681a-ef49-4687-a57d-5de56fa259ed', '{"created_at": "2024-12-02T15:23:10Z", "updated_at": "2024-12-02T15:23:10Z"}', 'DKI Jakarta', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('68a8677f-7154-4196-ab65-dc5a4acc5f6b', '{"created_at": "2024-12-02T15:23:38Z", "updated_at": "2024-12-02T15:23:38Z"}', 'Daerah Istimewa Yogyakarta', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('bf5a5d0d-7974-4bb3-a1bd-6050c9d319ad', '{"created_at": "2024-12-02T15:24:45Z", "updated_at": "2024-12-02T15:24:45Z"}', 'Gorontalo', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('c31743e2-6f47-4559-8cee-c8f2c43d96ed', '{"created_at": "2024-12-02T15:22:50Z", "updated_at": "2024-12-02T15:22:50Z"}', 'Jambi', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('c3467351-fdd3-43cf-b515-83a71b902e72', '{"created_at": "2024-12-02T15:23:11Z", "updated_at": "2024-12-02T15:23:11Z"}', 'Jawa Barat', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('b2a4dae1-4be0-4b6e-8bd1-3a5d6c8d9203', '{"created_at": "2024-12-02T15:23:25Z", "updated_at": "2024-12-02T15:23:25Z"}', 'Jawa Tengah', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('3f12898c-9faa-4585-9e0d-4799218bed86', '{"created_at": "2024-12-02T15:23:40Z", "updated_at": "2024-12-02T15:23:40Z"}', 'Jawa Timur', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('d6ce1e13-d1a6-4c3d-bc7c-b60e14238830', '{"created_at": "2024-12-02T15:24:10Z", "updated_at": "2024-12-02T15:24:10Z"}', 'Kalimantan Barat', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('58c01e45-a09a-4e10-8aca-acf4ec9ce152', '{"created_at": "2024-12-02T15:24:17Z", "updated_at": "2024-12-02T15:24:17Z"}', 'Kalimantan Selatan', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('126b1511-5d23-4fdf-9138-81a646c57f92', '{"created_at": "2024-12-02T15:24:14Z", "updated_at": "2024-12-02T15:24:14Z"}', 'Kalimantan Tengah', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('3a036675-406e-465f-a21f-441498750e4c', '{"created_at": "2024-12-02T15:24:21Z", "updated_at": "2024-12-02T15:24:21Z"}', 'Kalimantan Timur', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('481d160d-afda-4b86-b22b-05debdd9d068', '{"created_at": "2024-12-02T15:24:24Z", "updated_at": "2024-12-02T15:24:24Z"}', 'Kalimantan Utara', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('f3222f78-ab75-48bb-9fa6-d27318d671c7', '{"created_at": "2024-12-02T15:23:07Z", "updated_at": "2024-12-02T15:23:07Z"}', 'Kepulauan Bangka Belitung', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('6898b863-19c5-4b95-a272-d5d68fe6b5de', '{"created_at": "2024-12-02T15:23:08Z", "updated_at": "2024-12-02T15:23:08Z"}', 'Kepulauan Riau', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('4c995ebd-b1d9-44dd-a59d-3d21ac1309ec', '{"created_at": "2024-12-02T15:23:02Z", "updated_at": "2024-12-02T15:23:02Z"}', 'Lampung', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('10b2abc8-4c23-4ddf-adf4-8b9df1bdd10c', '{"created_at": "2024-12-02T15:24:48Z", "updated_at": "2024-12-02T15:24:48Z"}', 'Maluku', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('8055a6e1-74ff-4598-af13-202675d5f5ee', '{"created_at": "2024-12-02T15:24:51Z", "updated_at": "2024-12-02T15:24:51Z"}', 'Maluku Utara', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('4dd28f62-c8be-4379-a989-67d57fcbec53', '{"created_at": "2024-12-02T15:24:00Z", "updated_at": "2024-12-02T15:24:00Z"}', 'Nusa Tenggara Barat', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('71a3e735-9687-4a56-b73c-6dd29d7b33c6', '{"created_at": "2024-12-02T15:24:02Z", "updated_at": "2024-12-02T15:24:02Z"}', 'Nusa Tenggara Timur', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('835ad785-b109-40fb-b978-7283d9619035', '{"created_at": "2024-12-02T15:24:54Z", "updated_at": "2024-12-02T15:24:54Z"}', 'Papua', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('7469e13d-2e6a-4ad9-b9cd-c761136fad69', '{"created_at": "2024-12-02T15:24:59Z", "updated_at": "2024-12-02T15:24:59Z"}', 'Papua Barat', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('54743c28-eeb3-4f7c-a9c5-00dcd9d6bf57', '{"created_at": "2024-12-02T15:24:56Z", "updated_at": "2024-12-02T15:24:56Z"}', 'Papua Barat Daya', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('e6d909a6-055a-4fca-9bdb-efcd5dcf8227', '{"created_at": "2024-12-02T15:25:06Z", "updated_at": "2024-12-02T15:25:06Z"}', 'Papua Pegunungan', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('e79484af-3d78-4132-9418-2255624b88fd', '{"created_at": "2024-12-02T15:25:01Z", "updated_at": "2024-12-02T15:25:01Z"}', 'Papua Selatan', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('392ff50f-c8f4-48bc-b666-da7b4b5b2a1a', '{"created_at": "2024-12-02T15:25:03Z", "updated_at": "2024-12-02T15:25:03Z"}', 'Papua Tengah', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('dc694808-82a9-47da-b098-a9082109d13b', '{"created_at": "2024-12-02T15:22:46Z", "updated_at": "2024-12-02T15:22:46Z"}', 'Riau', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('5b359181-25c6-4ca5-a074-4b72467af14e', '{"created_at": "2024-12-02T15:24:47Z", "updated_at": "2024-12-02T15:24:47Z"}', 'Sulawesi Barat', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('aef8af79-8df9-43bc-a021-8b5fcbcabcb4', '{"created_at": "2024-12-02T15:24:33Z", "updated_at": "2024-12-02T15:24:33Z"}', 'Sulawesi Selatan', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('9aeceecb-ccd2-4f55-bed0-cc74e85abe99', '{"created_at": "2024-12-02T15:24:29Z", "updated_at": "2024-12-02T15:24:29Z"}', 'Sulawesi Tengah', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('c2752fa8-8fec-4dd2-bfff-7ce3dd8322e6', '{"created_at": "2024-12-02T15:24:40Z", "updated_at": "2024-12-02T15:24:40Z"}', 'Sulawesi Tenggara', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('5229810b-a0f6-4fd5-b1b4-66343f834cab', '{"created_at": "2024-12-02T15:24:25Z", "updated_at": "2024-12-02T15:24:25Z"}', 'Sulawesi Utara', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('79c6bbe5-de0b-4c5e-a966-71f6718b757a', '{"created_at": "2024-12-02T15:22:42Z", "updated_at": "2024-12-02T15:22:42Z"}', 'Sumatera Barat', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('05c3c676-35b2-4f4f-83a8-95e6f63dc65d', '{"created_at": "2024-12-02T15:22:53Z", "updated_at": "2024-12-02T15:22:53Z"}', 'Sumatera Selatan', '866f1b4e-a9f3-4626-95d1-13c183916b4b'),
('78b04f71-747e-4a52-ae54-118bf902d80e', '{"created_at": "2024-12-02T15:22:32Z", "updated_at": "2024-12-02T15:22:32Z"}', 'Sumatera Utara', '866f1b4e-a9f3-4626-95d1-13c183916b4b');