-- Migration: Create provinces table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS geo;

CREATE TABLE IF NOT EXISTS geo.provinces (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    country_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_provinces_country_id ON geo.provinces (country_id);

CREATE INDEX IF NOT EXISTS idx_provinces_name ON geo.provinces (name);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_provinces_metadata_gin ON geo.provinces USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_provinces_metadata_deleted_at ON geo.provinces ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_provinces_metadata_created_at ON geo.provinces ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_provinces_metadata_updated_at ON geo.provinces ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION geo.provinces_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS provinces_insert_audit ON geo.provinces;
CREATE TRIGGER provinces_insert_audit BEFORE INSERT ON geo.provinces
    FOR EACH ROW EXECUTE FUNCTION geo.provinces_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS provinces_update_audit ON geo.provinces;
CREATE TRIGGER provinces_update_audit BEFORE UPDATE ON geo.provinces
    FOR EACH ROW EXECUTE FUNCTION geo.provinces_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE geo.provinces ADD CONSTRAINT fk_provinces_country_id FOREIGN KEY (country_id) REFERENCES geo.countries (id);
