-- Migration: Create districts table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS geo;

CREATE TABLE IF NOT EXISTS geo.districts (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    country_id UUID NOT NULL,
    province_id UUID NOT NULL,
    city_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_districts_country_id ON geo.districts (country_id);

CREATE INDEX IF NOT EXISTS idx_districts_province_id ON geo.districts (province_id);

CREATE INDEX IF NOT EXISTS idx_districts_city_id ON geo.districts (city_id);

CREATE INDEX IF NOT EXISTS idx_districts_name ON geo.districts (name);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_districts_metadata_gin ON geo.districts USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_districts_metadata_deleted_at ON geo.districts ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_districts_metadata_created_at ON geo.districts ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_districts_metadata_updated_at ON geo.districts ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION geo.districts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS districts_insert_audit ON geo.districts;
CREATE TRIGGER districts_insert_audit BEFORE INSERT ON geo.districts
    FOR EACH ROW EXECUTE FUNCTION geo.districts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS districts_update_audit ON geo.districts;
CREATE TRIGGER districts_update_audit BEFORE UPDATE ON geo.districts
    FOR EACH ROW EXECUTE FUNCTION geo.districts_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE geo.districts ADD CONSTRAINT fk_districts_city_id FOREIGN KEY (city_id) REFERENCES geo.cities (id);
