-- Migration: Create subdistricts table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS geo;

CREATE TABLE IF NOT EXISTS geo.subdistricts (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    country_id UUID NOT NULL,
    province_id UUID NOT NULL,
    city_id UUID NOT NULL,
    district_id UUID NOT NULL,
    postal_code TEXT,
    latitude NUMERIC,
    longitude NUMERIC,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_subdistricts_district_id_name ON geo.subdistricts (district_id, name);

CREATE INDEX IF NOT EXISTS idx_subdistricts_country_id ON geo.subdistricts (country_id);

CREATE INDEX IF NOT EXISTS idx_subdistricts_province_id ON geo.subdistricts (province_id);

CREATE INDEX IF NOT EXISTS idx_subdistricts_city_id ON geo.subdistricts (city_id);

CREATE INDEX IF NOT EXISTS idx_subdistricts_district_id ON geo.subdistricts (district_id);

CREATE INDEX IF NOT EXISTS idx_subdistricts_postal_code ON geo.subdistricts (postal_code);

CREATE INDEX IF NOT EXISTS idx_subdistricts_name ON geo.subdistricts (name);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_subdistricts_metadata_gin ON geo.subdistricts USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_subdistricts_metadata_deleted_at ON geo.subdistricts ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_subdistricts_metadata_created_at ON geo.subdistricts ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_subdistricts_metadata_updated_at ON geo.subdistricts ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION geo.subdistricts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS subdistricts_insert_audit ON geo.subdistricts;
CREATE TRIGGER subdistricts_insert_audit BEFORE INSERT ON geo.subdistricts
    FOR EACH ROW EXECUTE FUNCTION geo.subdistricts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS subdistricts_update_audit ON geo.subdistricts;
CREATE TRIGGER subdistricts_update_audit BEFORE UPDATE ON geo.subdistricts
    FOR EACH ROW EXECUTE FUNCTION geo.subdistricts_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE geo.subdistricts ADD CONSTRAINT fk_subdistricts_district_id FOREIGN KEY (district_id) REFERENCES geo.districts (id);
