-- Migration: Create cities table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS geo;

CREATE TABLE IF NOT EXISTS geo.cities (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    country_id UUID NOT NULL,
    province_id UUID NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_cities_country_id ON geo.cities (country_id);

CREATE INDEX IF NOT EXISTS idx_cities_province_id ON geo.cities (province_id);

CREATE INDEX IF NOT EXISTS idx_cities_name ON geo.cities (name);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_cities_metadata_gin ON geo.cities USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_cities_metadata_deleted_at ON geo.cities ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_cities_metadata_created_at ON geo.cities ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_cities_metadata_updated_at ON geo.cities ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION geo.cities_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS cities_insert_audit ON geo.cities;
CREATE TRIGGER cities_insert_audit BEFORE INSERT ON geo.cities
    FOR EACH ROW EXECUTE FUNCTION geo.cities_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS cities_update_audit ON geo.cities;
CREATE TRIGGER cities_update_audit BEFORE UPDATE ON geo.cities
    FOR EACH ROW EXECUTE FUNCTION geo.cities_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE geo.cities ADD CONSTRAINT fk_cities_province_id FOREIGN KEY (province_id) REFERENCES geo.provinces (id);
