-- Migration: Create countries table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS geo;

CREATE TABLE IF NOT EXISTS geo.countries (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    isocode TEXT NOT NULL,
    name TEXT NOT NULL,
    phonecode INTEGER NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_countries_isocode ON geo.countries (isocode);

CREATE INDEX IF NOT EXISTS idx_countries_name ON geo.countries (name);

CREATE INDEX IF NOT EXISTS idx_countries_phonecode ON geo.countries (phonecode);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_countries_metadata_gin ON geo.countries USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_countries_metadata_deleted_at ON geo.countries ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_countries_metadata_created_at ON geo.countries ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_countries_metadata_updated_at ON geo.countries ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION geo.countries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS countries_insert_audit ON geo.countries;
CREATE TRIGGER countries_insert_audit BEFORE INSERT ON geo.countries
    FOR EACH ROW EXECUTE FUNCTION geo.countries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS countries_update_audit ON geo.countries;
CREATE TRIGGER countries_update_audit BEFORE UPDATE ON geo.countries
    FOR EACH ROW EXECUTE FUNCTION geo.countries_audit_timestamp();
