-- Audit Triggers Migration for geo module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: City (geo.cities)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION geo.cities_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS cities_insert_audit ON geo.cities;
CREATE TRIGGER cities_insert_audit BEFORE INSERT ON geo.cities
    FOR EACH ROW EXECUTE FUNCTION geo.cities_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS cities_update_audit ON geo.cities;
CREATE TRIGGER cities_update_audit BEFORE UPDATE ON geo.cities
    FOR EACH ROW EXECUTE FUNCTION geo.cities_audit_timestamp();

-- ==============================================================================
-- Table: Country (geo.countries)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION geo.countries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS countries_insert_audit ON geo.countries;
CREATE TRIGGER countries_insert_audit BEFORE INSERT ON geo.countries
    FOR EACH ROW EXECUTE FUNCTION geo.countries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS countries_update_audit ON geo.countries;
CREATE TRIGGER countries_update_audit BEFORE UPDATE ON geo.countries
    FOR EACH ROW EXECUTE FUNCTION geo.countries_audit_timestamp();

-- ==============================================================================
-- Table: District (geo.districts)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION geo.districts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS districts_insert_audit ON geo.districts;
CREATE TRIGGER districts_insert_audit BEFORE INSERT ON geo.districts
    FOR EACH ROW EXECUTE FUNCTION geo.districts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS districts_update_audit ON geo.districts;
CREATE TRIGGER districts_update_audit BEFORE UPDATE ON geo.districts
    FOR EACH ROW EXECUTE FUNCTION geo.districts_audit_timestamp();

-- ==============================================================================
-- Table: Province (geo.provinces)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION geo.provinces_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS provinces_insert_audit ON geo.provinces;
CREATE TRIGGER provinces_insert_audit BEFORE INSERT ON geo.provinces
    FOR EACH ROW EXECUTE FUNCTION geo.provinces_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS provinces_update_audit ON geo.provinces;
CREATE TRIGGER provinces_update_audit BEFORE UPDATE ON geo.provinces
    FOR EACH ROW EXECUTE FUNCTION geo.provinces_audit_timestamp();

-- ==============================================================================
-- Table: Subdistrict (geo.subdistricts)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION geo.subdistricts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS subdistricts_insert_audit ON geo.subdistricts;
CREATE TRIGGER subdistricts_insert_audit BEFORE INSERT ON geo.subdistricts
    FOR EACH ROW EXECUTE FUNCTION geo.subdistricts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS subdistricts_update_audit ON geo.subdistricts;
CREATE TRIGGER subdistricts_update_audit BEFORE UPDATE ON geo.subdistricts
    FOR EACH ROW EXECUTE FUNCTION geo.subdistricts_audit_timestamp();

