//! Domain events for City entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::City;

/// Domain events for City — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<City>)` variant.
pub type CityEvent = CrudEvent<City>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for City events.
pub type CityEventPublisher = Arc<dyn CrudEventPublisher<City> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopCityEventPublisher = NoOpCrudEventPublisher<City>;
