//! Event handler trait for City events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CityEvent;

/// Event handler for City events.
/// Implement this trait to react to City lifecycle events.
pub trait CityEventHandler: EventHandler<CityEvent> {}
