//! Event handler trait for Country events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::CountryEvent;

/// Event handler for Country events.
/// Implement this trait to react to Country lifecycle events.
pub trait CountryEventHandler: EventHandler<CountryEvent> {}
