//! Domain events for District entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::District;

/// Domain events for District — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<District>)` variant.
pub type DistrictEvent = CrudEvent<District>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for District events.
pub type DistrictEventPublisher = Arc<dyn CrudEventPublisher<District> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopDistrictEventPublisher = NoOpCrudEventPublisher<District>;
