//! Event handler trait for District events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::DistrictEvent;

/// Event handler for District events.
/// Implement this trait to react to District lifecycle events.
pub trait DistrictEventHandler: EventHandler<DistrictEvent> {}
