//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod city_events;
pub mod city_event_handlers;
pub mod country_events;
pub mod country_event_handlers;
pub mod district_events;
pub mod district_event_handlers;
pub mod province_events;
pub mod province_event_handlers;
pub mod subdistrict_events;
pub mod subdistrict_event_handlers;

pub use city_events::{CityEvent, CityEventPublisher, NoopCityEventPublisher};
pub use city_event_handlers::CityEventHandler;
pub use country_events::{CountryEvent, CountryEventPublisher, NoopCountryEventPublisher};
pub use country_event_handlers::CountryEventHandler;
pub use district_events::{DistrictEvent, DistrictEventPublisher, NoopDistrictEventPublisher};
pub use district_event_handlers::DistrictEventHandler;
pub use province_events::{ProvinceEvent, ProvinceEventPublisher, NoopProvinceEventPublisher};
pub use province_event_handlers::ProvinceEventHandler;
pub use subdistrict_events::{SubdistrictEvent, SubdistrictEventPublisher, NoopSubdistrictEventPublisher};
pub use subdistrict_event_handlers::SubdistrictEventHandler;

// <<< CUSTOM
// END CUSTOM
