//! Domain events for Province entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Province;

/// Domain events for Province — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Province>)` variant.
pub type ProvinceEvent = CrudEvent<Province>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Province events.
pub type ProvinceEventPublisher = Arc<dyn CrudEventPublisher<Province> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopProvinceEventPublisher = NoOpCrudEventPublisher<Province>;
