//! Event handler trait for Province events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ProvinceEvent;

/// Event handler for Province events.
/// Implement this trait to react to Province lifecycle events.
pub trait ProvinceEventHandler: EventHandler<ProvinceEvent> {}
