//! Event handler trait for Subdistrict events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SubdistrictEvent;

/// Event handler for Subdistrict events.
/// Implement this trait to react to Subdistrict lifecycle events.
pub trait SubdistrictEventHandler: EventHandler<SubdistrictEvent> {}
