//! Domain events for Subdistrict entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Subdistrict;

/// Domain events for Subdistrict — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Subdistrict>)` variant.
pub type SubdistrictEvent = CrudEvent<Subdistrict>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Subdistrict events.
pub type SubdistrictEventPublisher = Arc<dyn CrudEventPublisher<Subdistrict> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSubdistrictEventPublisher = NoOpCrudEventPublisher<Subdistrict>;
