//! Event subscriber type aliases for Geo module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::CityEvent;
use crate::domain::event::CountryEvent;
use crate::domain::event::DistrictEvent;
use crate::domain::event::ProvinceEvent;
use crate::domain::event::SubdistrictEvent;

/// Subscriber for City events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type CityEventSubscriber = GenericEventSubscriber<CityEvent>;

/// Subscriber for Country events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type CountryEventSubscriber = GenericEventSubscriber<CountryEvent>;

/// Subscriber for District events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type DistrictEventSubscriber = GenericEventSubscriber<DistrictEvent>;

/// Subscriber for Province events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ProvinceEventSubscriber = GenericEventSubscriber<ProvinceEvent>;

/// Subscriber for Subdistrict events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type SubdistrictEventSubscriber = GenericEventSubscriber<SubdistrictEvent>;

// <<< CUSTOM
// END CUSTOM
