//! City seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial City data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// CITY SEEDER
// ============================================================================

/// Seeder for city
pub struct SeedCitySeeder;

impl SeedCitySeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedCitySeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedCitySeeder {
    fn name(&self) -> &'static str {
        "SeedCitySeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if geo.cities table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM geo.cities")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/city_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM geo.cities")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

