//! Subdistrict seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial Subdistrict data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// SUBDISTRICT SEEDER
// ============================================================================

/// Seeder for subdistrict
pub struct SeedSubdistrictSeeder;

impl SeedSubdistrictSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedSubdistrictSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedSubdistrictSeeder {
    fn name(&self) -> &'static str {
        "SeedSubdistrictSeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if geo.subdistricts table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM geo.subdistricts")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/subdistrict_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM geo.subdistricts")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

