//! Repository trait for City aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the City aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::City;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CityPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CityPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CityPaginatedResult {
    pub data: Vec<City>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CityFilter {
    pub name: Option<String>,
    pub country_id: Option<Uuid>,
    pub province_id: Option<Uuid>,
}

impl CityFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.country_id.is_some() || self.province_id.is_some()
    }
}

/// Repository trait for City aggregate
///
/// This trait defines the persistence contract for City entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CityRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new city entity
    async fn save(&self, entity: &City) -> Result<City>;

    /// Find city by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<City>>;

    /// Find all city entities
    async fn find_all(&self) -> Result<Vec<City>>;

    /// Update city by ID
    async fn update(&self, id: &str, entity: &City) -> Result<Option<City>>;

    /// Delete city by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List city with pagination
    async fn list(&self, params: CityPaginationParams) -> Result<CityPaginatedResult>;

    /// List city with pagination and filters
    async fn list_with_filters(&self, params: CityPaginationParams, filters: CityFilter) -> Result<CityPaginatedResult>;

    /// Count all city entities
    async fn count(&self) -> Result<u64>;

    /// Count city entities matching filters
    async fn count_with_filters(&self, filters: CityFilter) -> Result<u64>;

    /// Check if city exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete city by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted city by ID
    async fn restore(&self, id: &str) -> Result<Option<City>>;

    /// List soft-deleted city entities
    async fn list_deleted(&self, params: CityPaginationParams) -> Result<CityPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save city entities
    async fn bulk_save(&self, entities: &[City]) -> Result<Vec<City>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
