//! Repository trait for Country aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Country aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::Country;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CountryPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl CountryPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct CountryPaginatedResult {
    pub data: Vec<Country>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct CountryFilter {
    pub isocode: Option<String>,
    pub name: Option<String>,
}

impl CountryFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.isocode.is_some() || self.name.is_some()
    }
}

/// Repository trait for Country aggregate
///
/// This trait defines the persistence contract for Country entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait CountryRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new country entity
    async fn save(&self, entity: &Country) -> Result<Country>;

    /// Find country by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Country>>;

    /// Find all country entities
    async fn find_all(&self) -> Result<Vec<Country>>;

    /// Update country by ID
    async fn update(&self, id: &str, entity: &Country) -> Result<Option<Country>>;

    /// Delete country by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List country with pagination
    async fn list(&self, params: CountryPaginationParams) -> Result<CountryPaginatedResult>;

    /// List country with pagination and filters
    async fn list_with_filters(&self, params: CountryPaginationParams, filters: CountryFilter) -> Result<CountryPaginatedResult>;

    /// Count all country entities
    async fn count(&self) -> Result<u64>;

    /// Count country entities matching filters
    async fn count_with_filters(&self, filters: CountryFilter) -> Result<u64>;

    /// Check if country exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete country by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted country by ID
    async fn restore(&self, id: &str) -> Result<Option<Country>>;

    /// List soft-deleted country entities
    async fn list_deleted(&self, params: CountryPaginationParams) -> Result<CountryPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save country entities
    async fn bulk_save(&self, entities: &[Country]) -> Result<Vec<Country>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
