//! Repository trait for District aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the District aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::District;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DistrictPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl DistrictPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct DistrictPaginatedResult {
    pub data: Vec<District>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DistrictFilter {
    pub name: Option<String>,
    pub country_id: Option<Uuid>,
    pub province_id: Option<Uuid>,
    pub city_id: Option<Uuid>,
}

impl DistrictFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.country_id.is_some() || self.province_id.is_some() || self.city_id.is_some()
    }
}

/// Repository trait for District aggregate
///
/// This trait defines the persistence contract for District entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait DistrictRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new district entity
    async fn save(&self, entity: &District) -> Result<District>;

    /// Find district by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<District>>;

    /// Find all district entities
    async fn find_all(&self) -> Result<Vec<District>>;

    /// Update district by ID
    async fn update(&self, id: &str, entity: &District) -> Result<Option<District>>;

    /// Delete district by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List district with pagination
    async fn list(&self, params: DistrictPaginationParams) -> Result<DistrictPaginatedResult>;

    /// List district with pagination and filters
    async fn list_with_filters(&self, params: DistrictPaginationParams, filters: DistrictFilter) -> Result<DistrictPaginatedResult>;

    /// Count all district entities
    async fn count(&self) -> Result<u64>;

    /// Count district entities matching filters
    async fn count_with_filters(&self, filters: DistrictFilter) -> Result<u64>;

    /// Check if district exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete district by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted district by ID
    async fn restore(&self, id: &str) -> Result<Option<District>>;

    /// List soft-deleted district entities
    async fn list_deleted(&self, params: DistrictPaginationParams) -> Result<DistrictPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save district entities
    async fn bulk_save(&self, entities: &[District]) -> Result<Vec<District>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
