//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod city_repository;
pub mod country_repository;
pub mod district_repository;
pub mod province_repository;
pub mod subdistrict_repository;

// Re-exports
pub use city_repository::{
    CityRepository,
    CityPaginationParams,
    CityPaginatedResult,
    CityFilter,
};
pub use country_repository::{
    CountryRepository,
    CountryPaginationParams,
    CountryPaginatedResult,
    CountryFilter,
};
pub use district_repository::{
    DistrictRepository,
    DistrictPaginationParams,
    DistrictPaginatedResult,
    DistrictFilter,
};
pub use province_repository::{
    ProvinceRepository,
    ProvincePaginationParams,
    ProvincePaginatedResult,
    ProvinceFilter,
};
pub use subdistrict_repository::{
    SubdistrictRepository,
    SubdistrictPaginationParams,
    SubdistrictPaginatedResult,
    SubdistrictFilter,
};
