//! Repository trait for Province aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Province aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::Province;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ProvincePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ProvincePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ProvincePaginatedResult {
    pub data: Vec<Province>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ProvinceFilter {
    pub name: Option<String>,
    pub country_id: Option<Uuid>,
}

impl ProvinceFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.country_id.is_some()
    }
}

/// Repository trait for Province aggregate
///
/// This trait defines the persistence contract for Province entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ProvinceRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new province entity
    async fn save(&self, entity: &Province) -> Result<Province>;

    /// Find province by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Province>>;

    /// Find all province entities
    async fn find_all(&self) -> Result<Vec<Province>>;

    /// Update province by ID
    async fn update(&self, id: &str, entity: &Province) -> Result<Option<Province>>;

    /// Delete province by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List province with pagination
    async fn list(&self, params: ProvincePaginationParams) -> Result<ProvincePaginatedResult>;

    /// List province with pagination and filters
    async fn list_with_filters(&self, params: ProvincePaginationParams, filters: ProvinceFilter) -> Result<ProvincePaginatedResult>;

    /// Count all province entities
    async fn count(&self) -> Result<u64>;

    /// Count province entities matching filters
    async fn count_with_filters(&self, filters: ProvinceFilter) -> Result<u64>;

    /// Check if province exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete province by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted province by ID
    async fn restore(&self, id: &str) -> Result<Option<Province>>;

    /// List soft-deleted province entities
    async fn list_deleted(&self, params: ProvincePaginationParams) -> Result<ProvincePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save province entities
    async fn bulk_save(&self, entities: &[Province]) -> Result<Vec<Province>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
