//! Repository trait for Subdistrict aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Subdistrict aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::Subdistrict;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SubdistrictPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SubdistrictPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SubdistrictPaginatedResult {
    pub data: Vec<Subdistrict>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SubdistrictFilter {
    pub name: Option<String>,
    pub country_id: Option<Uuid>,
    pub province_id: Option<Uuid>,
    pub city_id: Option<Uuid>,
    pub district_id: Option<Uuid>,
    pub postal_code: Option<String>,
}

impl SubdistrictFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.country_id.is_some() || self.province_id.is_some() || self.city_id.is_some() || self.district_id.is_some() || self.postal_code.is_some()
    }
}

/// Repository trait for Subdistrict aggregate
///
/// This trait defines the persistence contract for Subdistrict entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SubdistrictRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new subdistrict entity
    async fn save(&self, entity: &Subdistrict) -> Result<Subdistrict>;

    /// Find subdistrict by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Subdistrict>>;

    /// Find all subdistrict entities
    async fn find_all(&self) -> Result<Vec<Subdistrict>>;

    /// Update subdistrict by ID
    async fn update(&self, id: &str, entity: &Subdistrict) -> Result<Option<Subdistrict>>;

    /// Delete subdistrict by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List subdistrict with pagination
    async fn list(&self, params: SubdistrictPaginationParams) -> Result<SubdistrictPaginatedResult>;

    /// List subdistrict with pagination and filters
    async fn list_with_filters(&self, params: SubdistrictPaginationParams, filters: SubdistrictFilter) -> Result<SubdistrictPaginatedResult>;

    /// Count all subdistrict entities
    async fn count(&self) -> Result<u64>;

    /// Count subdistrict entities matching filters
    async fn count_with_filters(&self, filters: SubdistrictFilter) -> Result<u64>;

    /// Check if subdistrict exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete subdistrict by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted subdistrict by ID
    async fn restore(&self, id: &str) -> Result<Option<Subdistrict>>;

    /// List soft-deleted subdistrict entities
    async fn list_deleted(&self, params: SubdistrictPaginationParams) -> Result<SubdistrictPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save subdistrict entities
    async fn bulk_save(&self, entities: &[Subdistrict]) -> Result<Vec<Subdistrict>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
