//! Repository for Country entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom method
//! below holds the geo readiness guard's reference-count SQL (4-layer rule: services orchestrate,
//! repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Country, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Country;

/// Table name for Country entities
pub const TABLE_NAME: &str = "geo.countries";

/// Repository for Country entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct CountryRepository(
    backbone_orm::GenericCrudRepository<Country, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for CountryRepository {
    type Target = backbone_orm::GenericCrudRepository<Country, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl CountryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// Geo reference-data SQL. Lives here (not in the service) per the module's 4-layer rule.
impl CountryRepository {
    /// Total reference countries in `geo.countries`. The readiness guard uses this as the
    /// "is the seed loaded?" gate — zero countries means a fresh tenant would boot healthy
    /// with an empty geo. Bare-pool read: geo is a GLOBAL reference master with no company
    /// scope, so no `bind_company_on` / scoped helper applies.
    pub async fn count_all(pool: &PgPool) -> Result<i64, sqlx::Error> {
        sqlx::query_scalar("SELECT COUNT(*) FROM geo.countries")
            .fetch_one(pool)
            .await
    }
}

backbone_core::impl_crud_repository!(CountryRepository, Country, soft_delete);
