//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod city_repository;
mod country_repository;
mod district_repository;
mod province_repository;
mod subdistrict_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use city_repository::CityRepository;
pub use country_repository::CountryRepository;
pub use district_repository::DistrictRepository;
pub use province_repository::ProvinceRepository;
pub use subdistrict_repository::SubdistrictRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// END CUSTOM
