//! Repository for Subdistrict entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom method
//! below holds the geo readiness guard's denormalized-ancestor drift SQL (4-layer rule: services
//! orchestrate, repos hold SQL). The drift CTE is hosted here because it walks up FROM subdistricts
//! through districts/cities/provinces/countries — subdistrict is the deepest leaf of the chain.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Subdistrict, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Subdistrict;

/// Table name for Subdistrict entities
pub const TABLE_NAME: &str = "geo.subdistricts";

/// Repository for Subdistrict entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SubdistrictRepository(
    backbone_orm::GenericCrudRepository<Subdistrict, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SubdistrictRepository {
    type Target = backbone_orm::GenericCrudRepository<Subdistrict, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SubdistrictRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// Geo reference-data SQL. Lives here (not in the service) per the module's 4-layer rule.
impl SubdistrictRepository {
    /// Count rows whose denormalized ancestor ids disagree with their parent chain, summed across
    /// subdistrict/district/city levels. The readiness guard maps a non-zero result to
    /// `GeoReadinessError::AncestorDrift`. Bare-pool read: geo is a GLOBAL reference master with no
    /// company scope, so no `bind_company_on` / scoped helper applies. The SQL is preserved
    /// byte-identical to the prior inline form so plan/explain output is unchanged.
    pub async fn ancestor_drift_count(pool: &PgPool) -> Result<i64, sqlx::Error> {
        sqlx::query_scalar(
            r#"
        SELECT
          (SELECT COUNT(*) FROM geo.subdistricts s JOIN geo.districts d ON d.id = s.district_id
             WHERE s.city_id <> d.city_id OR s.province_id <> d.province_id OR s.country_id <> d.country_id)
        + (SELECT COUNT(*) FROM geo.districts d JOIN geo.cities c ON c.id = d.city_id
             WHERE d.province_id <> c.province_id OR d.country_id <> c.country_id)
        + (SELECT COUNT(*) FROM geo.cities c JOIN geo.provinces p ON p.id = c.province_id
             WHERE c.country_id <> p.country_id)
        "#,
        )
        .fetch_one(pool)
        .await
    }
}

backbone_core::impl_crud_repository!(SubdistrictRepository, Subdistrict, soft_delete);
