//! Repository for Subdistrict entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Subdistrict, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Subdistrict;

/// Table name for Subdistrict entities
pub const TABLE_NAME: &str = "geo.subdistricts";

/// Repository for Subdistrict entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SubdistrictRepository(
    backbone_orm::GenericCrudRepository<Subdistrict, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SubdistrictRepository {
    type Target = backbone_orm::GenericCrudRepository<Subdistrict, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SubdistrictRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(SubdistrictRepository, Subdistrict, soft_delete);
