//! Validator for City entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<City>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::City;

/// Validator type alias for City entities.
pub type CityValidator = EntityValidator<City>;

/// Build a validator for City with all schema-defined field rules.
pub fn city_validator() -> CityValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &City| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
