//! Validator for Country entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Country>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::Country;

/// Validator type alias for Country entities.
pub type CountryValidator = EntityValidator<Country>;

/// Build a validator for Country with all schema-defined field rules.
pub fn country_validator() -> CountryValidator {
    EntityValidator::new()
        .rule(RequiredString::new("isocode", |e: &Country| &e.isocode))
        .rule(RequiredString::new("name", |e: &Country| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
