//! Validator for District entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<District>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::District;

/// Validator type alias for District entities.
pub type DistrictValidator = EntityValidator<District>;

/// Build a validator for District with all schema-defined field rules.
pub fn district_validator() -> DistrictValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &District| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
