//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod city_validator;
pub mod country_validator;
pub mod district_validator;
pub mod province_validator;
pub mod subdistrict_validator;

pub use city_validator::{CityValidator, city_validator};
pub use country_validator::{CountryValidator, country_validator};
pub use district_validator::{DistrictValidator, district_validator};
pub use province_validator::{ProvinceValidator, province_validator};
pub use subdistrict_validator::{SubdistrictValidator, subdistrict_validator};

// <<< CUSTOM
// END CUSTOM
