//! Validator for Province entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Province>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::Province;

/// Validator type alias for Province entities.
pub type ProvinceValidator = EntityValidator<Province>;

/// Build a validator for Province with all schema-defined field rules.
pub fn province_validator() -> ProvinceValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &Province| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
