//! Validator for Subdistrict entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Subdistrict>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Subdistrict;

/// Validator type alias for Subdistrict entities.
pub type SubdistrictValidator = EntityValidator<Subdistrict>;

/// Build a validator for Subdistrict with all schema-defined field rules.
pub fn subdistrict_validator() -> SubdistrictValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &Subdistrict| &e.name))
        .rule(OptionalNotBlank::new("postal_code", |e: &Subdistrict| e.postal_code.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
