//! Auth configuration for City handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<City>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CityService;
use crate::domain::entity::City;

/// Permission string constants for City operations.
pub mod permissions {
    pub const LIST:        &str = "city:list";
    pub const READ:        &str = "city:read";
    pub const CREATE:      &str = "city:create";
    pub const UPDATE:      &str = "city:update";
    pub const DELETE:      &str = "city:delete";
    pub const RESTORE:     &str = "city:restore";
    pub const TRASH:       &str = "city:trash";
    pub const EMPTY_TRASH: &str = "city:empty_trash";
    pub const BULK_CREATE: &str = "city:bulk_create";
    pub const UPSERT:      &str = "city:upsert";
}

/// Resource policy for City — maps CRUD actions to permission strings.
pub struct CityPolicy;

#[async_trait]
impl ResourcePolicy<City> for CityPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &City,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for City handlers.
///
/// Wraps `CityService` and checks `CityPolicy` before delegating.
pub type CityGuard = PermissionGuard<City>;

/// Service-integrated permission guard for City (for use in generated handlers).
pub type CityServiceGuard = ServicePermissionGuard<City, CityService, CityPolicy>;

// <<< CUSTOM
// END CUSTOM
