//! Auth configuration for Country handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Country>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::CountryService;
use crate::domain::entity::Country;

/// Permission string constants for Country operations.
pub mod permissions {
    pub const LIST:        &str = "country:list";
    pub const READ:        &str = "country:read";
    pub const CREATE:      &str = "country:create";
    pub const UPDATE:      &str = "country:update";
    pub const DELETE:      &str = "country:delete";
    pub const RESTORE:     &str = "country:restore";
    pub const TRASH:       &str = "country:trash";
    pub const EMPTY_TRASH: &str = "country:empty_trash";
    pub const BULK_CREATE: &str = "country:bulk_create";
    pub const UPSERT:      &str = "country:upsert";
}

/// Resource policy for Country — maps CRUD actions to permission strings.
pub struct CountryPolicy;

#[async_trait]
impl ResourcePolicy<Country> for CountryPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Country,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Country handlers.
///
/// Wraps `CountryService` and checks `CountryPolicy` before delegating.
pub type CountryGuard = PermissionGuard<Country>;

/// Service-integrated permission guard for Country (for use in generated handlers).
pub type CountryServiceGuard = ServicePermissionGuard<Country, CountryService, CountryPolicy>;

// <<< CUSTOM
// END CUSTOM
