//! Auth configuration for District handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<District>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::DistrictService;
use crate::domain::entity::District;

/// Permission string constants for District operations.
pub mod permissions {
    pub const LIST:        &str = "district:list";
    pub const READ:        &str = "district:read";
    pub const CREATE:      &str = "district:create";
    pub const UPDATE:      &str = "district:update";
    pub const DELETE:      &str = "district:delete";
    pub const RESTORE:     &str = "district:restore";
    pub const TRASH:       &str = "district:trash";
    pub const EMPTY_TRASH: &str = "district:empty_trash";
    pub const BULK_CREATE: &str = "district:bulk_create";
    pub const UPSERT:      &str = "district:upsert";
}

/// Resource policy for District — maps CRUD actions to permission strings.
pub struct DistrictPolicy;

#[async_trait]
impl ResourcePolicy<District> for DistrictPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &District,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for District handlers.
///
/// Wraps `DistrictService` and checks `DistrictPolicy` before delegating.
pub type DistrictGuard = PermissionGuard<District>;

/// Service-integrated permission guard for District (for use in generated handlers).
pub type DistrictServiceGuard = ServicePermissionGuard<District, DistrictService, DistrictPolicy>;

// <<< CUSTOM
// END CUSTOM
