//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod city_auth;
pub mod country_auth;
pub mod district_auth;
pub mod province_auth;
pub mod subdistrict_auth;

pub use city_auth::{CityPolicy, CityGuard, CityServiceGuard};
pub use country_auth::{CountryPolicy, CountryGuard, CountryServiceGuard};
pub use district_auth::{DistrictPolicy, DistrictGuard, DistrictServiceGuard};
pub use province_auth::{ProvincePolicy, ProvinceGuard, ProvinceServiceGuard};
pub use subdistrict_auth::{SubdistrictPolicy, SubdistrictGuard, SubdistrictServiceGuard};

// <<< CUSTOM
// END CUSTOM
