//! Auth configuration for Province handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Province>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ProvinceService;
use crate::domain::entity::Province;

/// Permission string constants for Province operations.
pub mod permissions {
    pub const LIST:        &str = "province:list";
    pub const READ:        &str = "province:read";
    pub const CREATE:      &str = "province:create";
    pub const UPDATE:      &str = "province:update";
    pub const DELETE:      &str = "province:delete";
    pub const RESTORE:     &str = "province:restore";
    pub const TRASH:       &str = "province:trash";
    pub const EMPTY_TRASH: &str = "province:empty_trash";
    pub const BULK_CREATE: &str = "province:bulk_create";
    pub const UPSERT:      &str = "province:upsert";
}

/// Resource policy for Province — maps CRUD actions to permission strings.
pub struct ProvincePolicy;

#[async_trait]
impl ResourcePolicy<Province> for ProvincePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Province,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Province handlers.
///
/// Wraps `ProvinceService` and checks `ProvincePolicy` before delegating.
pub type ProvinceGuard = PermissionGuard<Province>;

/// Service-integrated permission guard for Province (for use in generated handlers).
pub type ProvinceServiceGuard = ServicePermissionGuard<Province, ProvinceService, ProvincePolicy>;

// <<< CUSTOM
// END CUSTOM
