//! Auth configuration for Subdistrict handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Subdistrict>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SubdistrictService;
use crate::domain::entity::Subdistrict;

/// Permission string constants for Subdistrict operations.
pub mod permissions {
    pub const LIST:        &str = "subdistrict:list";
    pub const READ:        &str = "subdistrict:read";
    pub const CREATE:      &str = "subdistrict:create";
    pub const UPDATE:      &str = "subdistrict:update";
    pub const DELETE:      &str = "subdistrict:delete";
    pub const RESTORE:     &str = "subdistrict:restore";
    pub const TRASH:       &str = "subdistrict:trash";
    pub const EMPTY_TRASH: &str = "subdistrict:empty_trash";
    pub const BULK_CREATE: &str = "subdistrict:bulk_create";
    pub const UPSERT:      &str = "subdistrict:upsert";
}

/// Resource policy for Subdistrict — maps CRUD actions to permission strings.
pub struct SubdistrictPolicy;

#[async_trait]
impl ResourcePolicy<Subdistrict> for SubdistrictPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Subdistrict,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Subdistrict handlers.
///
/// Wraps `SubdistrictService` and checks `SubdistrictPolicy` before delegating.
pub type SubdistrictGuard = PermissionGuard<Subdistrict>;

/// Service-integrated permission guard for Subdistrict (for use in generated handlers).
pub type SubdistrictServiceGuard = ServicePermissionGuard<Subdistrict, SubdistrictService, SubdistrictPolicy>;

// <<< CUSTOM
// END CUSTOM
