//! City API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the City CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// CITY TEST DATA GENERATOR
// ============================================================================

/// Test data generator for City
pub struct CityTestData;

impl TestDataGenerator for CityTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "country_id": Uuid::new_v4().to_string(),
            "province_id": Uuid::new_v4().to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "country_id": Uuid::new_v4().to_string(),
            "province_id": Uuid::new_v4().to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/countries", &super::country_api_test::CountryTestData).await {
            deps.push(("country_id".to_string(), id));
        }
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/provinces", &super::province_api_test::ProvinceTestData).await {
            deps.push(("province_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// CITY API TEST
// ============================================================================

/// City API test suite
pub struct CityApiTest {
    inner: GenericCrudTest<CityTestData>,
}

impl CityApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/cities", "City");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, CityTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for CityApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_city_crud() {
        let mut test = CityApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add City specific tests here
// <<< CUSTOM TESTS END >>>
