//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod city_api_test;
pub mod country_api_test;
pub mod district_api_test;
pub mod province_api_test;
pub mod subdistrict_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use city_api_test::*;
pub use country_api_test::*;
pub use district_api_test::*;
pub use province_api_test::*;
pub use subdistrict_api_test::*;
