//! Province API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Province CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PROVINCE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Province
pub struct ProvinceTestData;

impl TestDataGenerator for ProvinceTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "country_id": Uuid::new_v4().to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "country_id": Uuid::new_v4().to_string(),
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/countries", &super::country_api_test::CountryTestData).await {
            deps.push(("country_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// PROVINCE API TEST
// ============================================================================

/// Province API test suite
pub struct ProvinceApiTest {
    inner: GenericCrudTest<ProvinceTestData>,
}

impl ProvinceApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/provinces", "Province");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ProvinceTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ProvinceApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_province_crud() {
        let mut test = ProvinceApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Province specific tests here
// <<< CUSTOM TESTS END >>>
