//! Subdistrict API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Subdistrict CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SUBDISTRICT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Subdistrict
pub struct SubdistrictTestData;

impl TestDataGenerator for SubdistrictTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "country_id": Uuid::new_v4().to_string(),
            "province_id": Uuid::new_v4().to_string(),
            "city_id": Uuid::new_v4().to_string(),
            "district_id": Uuid::new_v4().to_string(),
            "postal_code": null,
            "latitude": null,
            "longitude": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "country_id": Uuid::new_v4().to_string(),
            "province_id": Uuid::new_v4().to_string(),
            "city_id": Uuid::new_v4().to_string(),
            "district_id": Uuid::new_v4().to_string(),
            "postal_code": null,
            "latitude": null,
            "longitude": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/countries", &super::country_api_test::CountryTestData).await {
            deps.push(("country_id".to_string(), id));
        }
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/provinces", &super::province_api_test::ProvinceTestData).await {
            deps.push(("province_id".to_string(), id));
        }
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/cities", &super::city_api_test::CityTestData).await {
            deps.push(("city_id".to_string(), id));
        }
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/districts", &super::district_api_test::DistrictTestData).await {
            deps.push(("district_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// SUBDISTRICT API TEST
// ============================================================================

/// Subdistrict API test suite
pub struct SubdistrictApiTest {
    inner: GenericCrudTest<SubdistrictTestData>,
}

impl SubdistrictApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/subdistricts", "Subdistrict");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, SubdistrictTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for SubdistrictApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_subdistrict_crud() {
        let mut test = SubdistrictApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Subdistrict specific tests here
// <<< CUSTOM TESTS END >>>
