//! Geo Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::CityService;
use crate::application::service::CountryService;
use crate::application::service::DistrictService;
use crate::application::service::ProvinceService;
use crate::application::service::SubdistrictService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// City service
    pub city_service: Arc<CityService>,
    /// Country service
    pub country_service: Arc<CountryService>,
    /// District service
    pub district_service: Arc<DistrictService>,
    /// Province service
    pub province_service: Arc<ProvinceService>,
    /// Subdistrict service
    pub subdistrict_service: Arc<SubdistrictService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        city_service: Arc<CityService>,
        country_service: Arc<CountryService>,
        district_service: Arc<DistrictService>,
        province_service: Arc<ProvinceService>,
        subdistrict_service: Arc<SubdistrictService>
    ) -> Self {
        Self {
            city_service,
            country_service,
            district_service,
            province_service,
            subdistrict_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::GeoModule) -> Self {
        Self {
            city_service: module.city_service.clone(),
            country_service: module.country_service.clone(),
            district_service: module.district_service.clone(),
            province_service: module.province_service.clone(),
            subdistrict_service: module.subdistrict_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    city_service: Option<Arc<CityService>>,
    country_service: Option<Arc<CountryService>>,
    district_service: Option<Arc<DistrictService>>,
    province_service: Option<Arc<ProvinceService>>,
    subdistrict_service: Option<Arc<SubdistrictService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the City service.
    pub fn with_city_service(mut self, service: Arc<CityService>) -> Self {
        self.city_service = Some(service);
        self
    }

    /// Set the Country service.
    pub fn with_country_service(mut self, service: Arc<CountryService>) -> Self {
        self.country_service = Some(service);
        self
    }

    /// Set the District service.
    pub fn with_district_service(mut self, service: Arc<DistrictService>) -> Self {
        self.district_service = Some(service);
        self
    }

    /// Set the Province service.
    pub fn with_province_service(mut self, service: Arc<ProvinceService>) -> Self {
        self.province_service = Some(service);
        self
    }

    /// Set the Subdistrict service.
    pub fn with_subdistrict_service(mut self, service: Arc<SubdistrictService>) -> Self {
        self.subdistrict_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            city_service: self.city_service.expect("city_service is required"),
            country_service: self.country_service.expect("country_service is required"),
            district_service: self.district_service.expect("district_service is required"),
            province_service: self.province_service.expect("province_service is required"),
            subdistrict_service: self.subdistrict_service.expect("subdistrict_service is required"),
        }
    }
}
