//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    city_handler::create_city_routes,
    country_handler::create_country_routes,
    district_handler::create_district_routes,
    province_handler::create_province_routes,
    subdistrict_handler::create_subdistrict_routes,
};

use crate::application::service::{
    CityService,
    CountryService,
    DistrictService,
    ProvinceService,
    SubdistrictService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub city: Arc<CityService>,
    pub country: Arc<CountryService>,
    pub district: Arc<DistrictService>,
    pub province: Arc<ProvinceService>,
    pub subdistrict: Arc<SubdistrictService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // City routes (12 Backbone endpoints)
        .merge(create_city_routes(services.city))
        // Country routes (12 Backbone endpoints)
        .merge(create_country_routes(services.country))
        // District routes (12 Backbone endpoints)
        .merge(create_district_routes(services.district))
        // Province routes (12 Backbone endpoints)
        .merge(create_province_routes(services.province))
        // Subdistrict routes (12 Backbone endpoints)
        .merge(create_subdistrict_routes(services.subdistrict))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn city_routes(service: Arc<CityService>) -> Router {
        create_city_routes(service)
    }

    pub fn country_routes(service: Arc<CountryService>) -> Router {
        create_country_routes(service)
    }

    pub fn district_routes(service: Arc<DistrictService>) -> Router {
        create_district_routes(service)
    }

    pub fn province_routes(service: Arc<ProvinceService>) -> Router {
        create_province_routes(service)
    }

    pub fn subdistrict_routes(service: Arc<SubdistrictService>) -> Router {
        create_subdistrict_routes(service)
    }

}
