//! Public events for Geo module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// CITY EVENTS
// ============================================================================

/// Event published when a City is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CityCreatedEvent {
    pub id: CityId,
    pub data: CityDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a City is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CityUpdatedEvent {
    pub id: CityId,
    pub data: CityDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a City is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CityDeletedEvent {
    pub id: CityId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// COUNTRY EVENTS
// ============================================================================

/// Event published when a Country is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CountryCreatedEvent {
    pub id: CountryId,
    pub data: CountryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Country is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CountryUpdatedEvent {
    pub id: CountryId,
    pub data: CountryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Country is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CountryDeletedEvent {
    pub id: CountryId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// DISTRICT EVENTS
// ============================================================================

/// Event published when a District is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DistrictCreatedEvent {
    pub id: DistrictId,
    pub data: DistrictDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a District is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DistrictUpdatedEvent {
    pub id: DistrictId,
    pub data: DistrictDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a District is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DistrictDeletedEvent {
    pub id: DistrictId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PROVINCE EVENTS
// ============================================================================

/// Event published when a Province is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvinceCreatedEvent {
    pub id: ProvinceId,
    pub data: ProvinceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Province is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvinceUpdatedEvent {
    pub id: ProvinceId,
    pub data: ProvinceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Province is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvinceDeletedEvent {
    pub id: ProvinceId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SUBDISTRICT EVENTS
// ============================================================================

/// Event published when a Subdistrict is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubdistrictCreatedEvent {
    pub id: SubdistrictId,
    pub data: SubdistrictDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Subdistrict is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubdistrictUpdatedEvent {
    pub id: SubdistrictId,
    pub data: SubdistrictDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Subdistrict is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubdistrictDeletedEvent {
    pub id: SubdistrictId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Geo module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum GeoEvent {
    CityCreated(CityCreatedEvent),
    CityUpdated(CityUpdatedEvent),
    CityDeleted(CityDeletedEvent),
    CountryCreated(CountryCreatedEvent),
    CountryUpdated(CountryUpdatedEvent),
    CountryDeleted(CountryDeletedEvent),
    DistrictCreated(DistrictCreatedEvent),
    DistrictUpdated(DistrictUpdatedEvent),
    DistrictDeleted(DistrictDeletedEvent),
    ProvinceCreated(ProvinceCreatedEvent),
    ProvinceUpdated(ProvinceUpdatedEvent),
    ProvinceDeleted(ProvinceDeletedEvent),
    SubdistrictCreated(SubdistrictCreatedEvent),
    SubdistrictUpdated(SubdistrictUpdatedEvent),
    SubdistrictDeleted(SubdistrictDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeoEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for GeoEventMetadata {
    fn default() -> Self {
        Self {
            module: "geo",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
