//! Geo Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Geo exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use geo::exports::{CityDto, GeoQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `CityDto` - Data transfer object for City
/// - `CitySummary` - Summary view of City
/// - `CityId` - Type-safe ID wrapper
/// - `CountryDto` - Data transfer object for Country
/// - `CountrySummary` - Summary view of Country
/// - `CountryId` - Type-safe ID wrapper
/// - `DistrictDto` - Data transfer object for District
/// - `DistrictSummary` - Summary view of District
/// - `DistrictId` - Type-safe ID wrapper
/// - `ProvinceDto` - Data transfer object for Province
/// - `ProvinceSummary` - Summary view of Province
/// - `ProvinceId` - Type-safe ID wrapper
/// - `SubdistrictDto` - Data transfer object for Subdistrict
/// - `SubdistrictSummary` - Summary view of Subdistrict
/// - `SubdistrictId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `GeoQueryService` - Read-only queries
///
/// ## Public Events
/// - `CityCreatedEvent` - Published when City is created
/// - `CityUpdatedEvent` - Published when City is updated
/// - `CityDeletedEvent` - Published when City is deleted
/// - `CountryCreatedEvent` - Published when Country is created
/// - `CountryUpdatedEvent` - Published when Country is updated
/// - `CountryDeletedEvent` - Published when Country is deleted
/// - `DistrictCreatedEvent` - Published when District is created
/// - `DistrictUpdatedEvent` - Published when District is updated
/// - `DistrictDeletedEvent` - Published when District is deleted
/// - `ProvinceCreatedEvent` - Published when Province is created
/// - `ProvinceUpdatedEvent` - Published when Province is updated
/// - `ProvinceDeletedEvent` - Published when Province is deleted
/// - `SubdistrictCreatedEvent` - Published when Subdistrict is created
/// - `SubdistrictUpdatedEvent` - Published when Subdistrict is updated
/// - `SubdistrictDeletedEvent` - Published when Subdistrict is deleted
pub struct ExportSummary;
