//! Public services for Geo module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Geo module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait GeoQueryService: Send + Sync {
    /// Get City by ID
    async fn get_city(&self, id: CityId) -> Result<Option<CityDto>>;

    /// Get City summary by ID
    async fn get_city_summary(&self, id: CityId) -> Result<Option<CitySummary>>;

    /// Check if City exists
    async fn city_exists(&self, id: CityId) -> Result<bool>;

    /// Get Country by ID
    async fn get_country(&self, id: CountryId) -> Result<Option<CountryDto>>;

    /// Get Country summary by ID
    async fn get_country_summary(&self, id: CountryId) -> Result<Option<CountrySummary>>;

    /// Check if Country exists
    async fn country_exists(&self, id: CountryId) -> Result<bool>;

    /// Get District by ID
    async fn get_district(&self, id: DistrictId) -> Result<Option<DistrictDto>>;

    /// Get District summary by ID
    async fn get_district_summary(&self, id: DistrictId) -> Result<Option<DistrictSummary>>;

    /// Check if District exists
    async fn district_exists(&self, id: DistrictId) -> Result<bool>;

    /// Get Province by ID
    async fn get_province(&self, id: ProvinceId) -> Result<Option<ProvinceDto>>;

    /// Get Province summary by ID
    async fn get_province_summary(&self, id: ProvinceId) -> Result<Option<ProvinceSummary>>;

    /// Check if Province exists
    async fn province_exists(&self, id: ProvinceId) -> Result<bool>;

    /// Get Subdistrict by ID
    async fn get_subdistrict(&self, id: SubdistrictId) -> Result<Option<SubdistrictDto>>;

    /// Get Subdistrict summary by ID
    async fn get_subdistrict_summary(&self, id: SubdistrictId) -> Result<Option<SubdistrictSummary>>;

    /// Check if Subdistrict exists
    async fn subdistrict_exists(&self, id: SubdistrictId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of GeoQueryService
pub struct GeoQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> GeoQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
