//! Public types for Geo module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// CITY TYPES
// ============================================================================

/// Type-safe ID for City
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CityId(pub Uuid);

impl CityId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CityId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CityId> for Uuid {
    fn from(id: CityId) -> Self {
        id.0
    }
}

/// Data transfer object for City
///
/// This is the public representation of City for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CityDto {
    pub id: CityId,
    pub name: String,
    pub country_id: Uuid,
    pub province_id: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of City for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CitySummary {
    pub id: CityId,
    pub name: String,
}

/// Reference to City for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CityRef {
    pub id: CityId,
}

// ============================================================================
// COUNTRY TYPES
// ============================================================================

/// Type-safe ID for Country
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct CountryId(pub Uuid);

impl CountryId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for CountryId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<CountryId> for Uuid {
    fn from(id: CountryId) -> Self {
        id.0
    }
}

/// Data transfer object for Country
///
/// This is the public representation of Country for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CountryDto {
    pub id: CountryId,
    pub isocode: String,
    pub name: String,
    pub phonecode: i32,
    pub metadata: serde_json::Value,
}

/// Summary view of Country for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CountrySummary {
    pub id: CountryId,
    pub name: String,
}

/// Reference to Country for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CountryRef {
    pub id: CountryId,
}

// ============================================================================
// DISTRICT TYPES
// ============================================================================

/// Type-safe ID for District
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct DistrictId(pub Uuid);

impl DistrictId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for DistrictId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<DistrictId> for Uuid {
    fn from(id: DistrictId) -> Self {
        id.0
    }
}

/// Data transfer object for District
///
/// This is the public representation of District for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DistrictDto {
    pub id: DistrictId,
    pub name: String,
    pub country_id: Uuid,
    pub province_id: Uuid,
    pub city_id: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of District for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DistrictSummary {
    pub id: DistrictId,
    pub name: String,
}

/// Reference to District for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DistrictRef {
    pub id: DistrictId,
}

// ============================================================================
// PROVINCE TYPES
// ============================================================================

/// Type-safe ID for Province
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ProvinceId(pub Uuid);

impl ProvinceId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ProvinceId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ProvinceId> for Uuid {
    fn from(id: ProvinceId) -> Self {
        id.0
    }
}

/// Data transfer object for Province
///
/// This is the public representation of Province for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvinceDto {
    pub id: ProvinceId,
    pub name: String,
    pub country_id: Uuid,
    pub metadata: serde_json::Value,
}

/// Summary view of Province for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvinceSummary {
    pub id: ProvinceId,
    pub name: String,
}

/// Reference to Province for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvinceRef {
    pub id: ProvinceId,
}

// ============================================================================
// SUBDISTRICT TYPES
// ============================================================================

/// Type-safe ID for Subdistrict
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SubdistrictId(pub Uuid);

impl SubdistrictId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SubdistrictId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SubdistrictId> for Uuid {
    fn from(id: SubdistrictId) -> Self {
        id.0
    }
}

/// Data transfer object for Subdistrict
///
/// This is the public representation of Subdistrict for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubdistrictDto {
    pub id: SubdistrictId,
    pub name: String,
    pub country_id: Uuid,
    pub province_id: Uuid,
    pub city_id: Uuid,
    pub district_id: Uuid,
    pub postal_code: Option<String>,
    pub latitude: Option<Decimal>,
    pub longitude: Option<Decimal>,
    pub metadata: serde_json::Value,
}

/// Summary view of Subdistrict for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubdistrictSummary {
    pub id: SubdistrictId,
    pub name: String,
}

/// Reference to Subdistrict for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubdistrictRef {
    pub id: SubdistrictId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
