//! Geo Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::CityService;
pub use application::service::CountryService;
pub use application::service::DistrictService;
pub use application::service::ProvinceService;
pub use application::service::SubdistrictService;

// <<< CUSTOM
pub use presentation::http::create_guarded_geo_routes;
pub use application::service::{ancestor_drift_count, geo_readiness_check, GeoReadinessError};
// END CUSTOM
use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Geo module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let geo = GeoModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = geo.all_crud_routes();
/// ```
pub struct GeoModule {
    pub(crate) city_service: Arc<CityService>,
    pub(crate) country_service: Arc<CountryService>,
    pub(crate) district_service: Arc<DistrictService>,
    pub(crate) province_service: Arc<ProvinceService>,
    pub(crate) subdistrict_service: Arc<SubdistrictService>,
    // <<< CUSTOM FIELDS
    // END CUSTOM
}

impl GeoModule {
    /// Create a new module builder
    pub fn builder() -> GeoModuleBuilder {
        GeoModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_city_routes,
            create_country_routes,
            create_district_routes,
            create_province_routes,
            create_subdistrict_routes,
        };

        Router::new()
            .merge(create_city_routes(self.city_service.clone()))
            .merge(create_country_routes(self.country_service.clone()))
            .merge(create_district_routes(self.district_service.clone()))
            .merge(create_province_routes(self.province_service.clone()))
            .merge(create_subdistrict_routes(self.subdistrict_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_city_read_routes,
            create_country_read_routes,
            create_district_read_routes,
            create_province_read_routes,
            create_subdistrict_read_routes,
        };

        Router::new()
            .merge(create_city_read_routes(self.city_service.clone()))
            .merge(create_country_read_routes(self.country_service.clone()))
            .merge(create_district_read_routes(self.district_service.clone()))
            .merge(create_province_read_routes(self.province_service.clone()))
            .merge(create_subdistrict_read_routes(self.subdistrict_service.clone()))
    }

    // <<< CUSTOM METHODS
    // END CUSTOM
}

/// Builder for GeoModule
pub struct GeoModuleBuilder {
    db_pool: Option<PgPool>,
}

impl GeoModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<GeoModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // City service
        let city_repository = Arc::new(CityRepository::new(db_pool.clone()));
        let city_service = Arc::new(CityService::with_repository(city_repository.clone()));

        // Country service
        let country_repository = Arc::new(CountryRepository::new(db_pool.clone()));
        let country_service = Arc::new(CountryService::with_repository(country_repository.clone()));

        // District service
        let district_repository = Arc::new(DistrictRepository::new(db_pool.clone()));
        let district_service = Arc::new(DistrictService::with_repository(district_repository.clone()));

        // Province service
        let province_repository = Arc::new(ProvinceRepository::new(db_pool.clone()));
        let province_service = Arc::new(ProvinceService::with_repository(province_repository.clone()));

        // Subdistrict service
        let subdistrict_repository = Arc::new(SubdistrictRepository::new(db_pool.clone()));
        let subdistrict_service = Arc::new(SubdistrictService::with_repository(subdistrict_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(GeoModule {
            city_service,
            country_service,
            district_service,
            province_service,
            subdistrict_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for GeoModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
