//! Use case type aliases for City aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCityDto, UpdateCityDto};
use crate::application::service::CityService;
use crate::domain::entity::City;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCityUseCase = CreateUseCase<City, CreateCityDto, CityService>;
pub type UpdateCityUseCase = UpdateUseCase<City, UpdateCityDto, CityService>;
pub type GetCityUseCase    = GetUseCase<City, CityService>;
pub type DeleteCityUseCase = DeleteUseCase<City, CityService>;
pub type ListCityUseCase   = ListUseCase<City, CityService>;

// <<< CUSTOM
// END CUSTOM
