//! Use case type aliases for Country aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateCountryDto, UpdateCountryDto};
use crate::application::service::CountryService;
use crate::domain::entity::Country;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateCountryUseCase = CreateUseCase<Country, CreateCountryDto, CountryService>;
pub type UpdateCountryUseCase = UpdateUseCase<Country, UpdateCountryDto, CountryService>;
pub type GetCountryUseCase    = GetUseCase<Country, CountryService>;
pub type DeleteCountryUseCase = DeleteUseCase<Country, CountryService>;
pub type ListCountryUseCase   = ListUseCase<Country, CountryService>;

// <<< CUSTOM
// END CUSTOM
