//! Use case type aliases for District aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateDistrictDto, UpdateDistrictDto};
use crate::application::service::DistrictService;
use crate::domain::entity::District;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateDistrictUseCase = CreateUseCase<District, CreateDistrictDto, DistrictService>;
pub type UpdateDistrictUseCase = UpdateUseCase<District, UpdateDistrictDto, DistrictService>;
pub type GetDistrictUseCase    = GetUseCase<District, DistrictService>;
pub type DeleteDistrictUseCase = DeleteUseCase<District, DistrictService>;
pub type ListDistrictUseCase   = ListUseCase<District, DistrictService>;

// <<< CUSTOM
// END CUSTOM
