//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod city_usecases;
pub mod country_usecases;
pub mod district_usecases;
pub mod province_usecases;
pub mod subdistrict_usecases;

pub use city_usecases::{
    CreateCityUseCase, UpdateCityUseCase, GetCityUseCase,
    DeleteCityUseCase, ListCityUseCase,
};
pub use country_usecases::{
    CreateCountryUseCase, UpdateCountryUseCase, GetCountryUseCase,
    DeleteCountryUseCase, ListCountryUseCase,
};
pub use district_usecases::{
    CreateDistrictUseCase, UpdateDistrictUseCase, GetDistrictUseCase,
    DeleteDistrictUseCase, ListDistrictUseCase,
};
pub use province_usecases::{
    CreateProvinceUseCase, UpdateProvinceUseCase, GetProvinceUseCase,
    DeleteProvinceUseCase, ListProvinceUseCase,
};
pub use subdistrict_usecases::{
    CreateSubdistrictUseCase, UpdateSubdistrictUseCase, GetSubdistrictUseCase,
    DeleteSubdistrictUseCase, ListSubdistrictUseCase,
};

// <<< CUSTOM
// END CUSTOM
