//! Use case type aliases for Province aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateProvinceDto, UpdateProvinceDto};
use crate::application::service::ProvinceService;
use crate::domain::entity::Province;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateProvinceUseCase = CreateUseCase<Province, CreateProvinceDto, ProvinceService>;
pub type UpdateProvinceUseCase = UpdateUseCase<Province, UpdateProvinceDto, ProvinceService>;
pub type GetProvinceUseCase    = GetUseCase<Province, ProvinceService>;
pub type DeleteProvinceUseCase = DeleteUseCase<Province, ProvinceService>;
pub type ListProvinceUseCase   = ListUseCase<Province, ProvinceService>;

// <<< CUSTOM
// END CUSTOM
