//! Use case type aliases for Subdistrict aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateSubdistrictDto, UpdateSubdistrictDto};
use crate::application::service::SubdistrictService;
use crate::domain::entity::Subdistrict;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateSubdistrictUseCase = CreateUseCase<Subdistrict, CreateSubdistrictDto, SubdistrictService>;
pub type UpdateSubdistrictUseCase = UpdateUseCase<Subdistrict, UpdateSubdistrictDto, SubdistrictService>;
pub type GetSubdistrictUseCase    = GetUseCase<Subdistrict, SubdistrictService>;
pub type DeleteSubdistrictUseCase = DeleteUseCase<Subdistrict, SubdistrictService>;
pub type ListSubdistrictUseCase   = ListUseCase<Subdistrict, SubdistrictService>;

// <<< CUSTOM
// END CUSTOM
