//! HTTP handlers
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod city_handler;
pub mod country_handler;
pub mod district_handler;
pub mod province_handler;
pub mod subdistrict_handler;

// <<< CUSTOM
pub mod guarded_routes;
// END CUSTOM

// Re-exports
pub use city_handler::{create_city_routes, create_city_read_routes, create_city_write_routes};
pub use country_handler::{create_country_routes, create_country_read_routes, create_country_write_routes};
pub use district_handler::{create_district_routes, create_district_read_routes, create_district_write_routes};
pub use province_handler::{create_province_routes, create_province_read_routes, create_province_write_routes};
pub use subdistrict_handler::{create_subdistrict_routes, create_subdistrict_read_routes, create_subdistrict_write_routes};
// <<< CUSTOM
pub use guarded_routes::create_guarded_geo_routes;
// END CUSTOM